package estudo.uanderson.javadevdojo.javacore.Jmodificadofinal.dominio;

public class Ferrari extends Carro{
/*
    public void imprime(){

    }
*/

    /*
    USO DO MODIFICADOR FINAL, ESTÁ EXTREMAMENTE LIGADO A HERENÇA

    COMPORTAMENTO EM CLASSE E MÉTODOS:
    -SE UTILIZADO EM CLASSES SIGNIFICA DIZER QUE A CLASSE NÃO PODERÁ SE
    EXTENDIDAR POR OUTRAS CLASSES.
    - SE UTILIZADO EM MÉTODOS, SIGNIFICA DIZER QUE OS MÉTODOS NÃO PODERAM
    SER SOBREESCRITOS EM CLASSES QUE HERDEM DA SUPERCLASSE.

    OBS: SE UTILIZADO O FINAL EM UMA CLASSE, NÃO É PRECISO DECLARAR MÉTODOS
    COM A CLAUSULA FINAL, POIS GERA REDUNDÂNCIA.
     */


}
